# image: docker:git
# services:
# - docker:dind

# stages:
# - build
# - test
# - release

# variables:
#   CONTAINER_TEST_IMAGE: registry.gitlab.com/tramwayjs/tramway-connection-example:$CI_BUILD_REF_NAME
#   CONTAINER_RELEASE_IMAGE: registry.gitlab.com/tramwayjs/tramway-connection-example:latest

# before_script:
#   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

# build:
#   stage: build
#   script:
#     - docker build -t $CONTAINER_TEST_IMAGE .
#     - docker push $CONTAINER_TEST_IMAGE

# test:
#   stage: test
#   script:
#     - docker run $CONTAINER_TEST_IMAGE npm test

# release-image:
#   stage: release
#   script:
#     - docker pull $CONTAINER_TEST_IMAGE
#     - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
#     - docker push $CONTAINER_RELEASE_IMAGE
#   only:
#     - master